config/routes.rb
Rails.application.routes.draw do
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    get 'posts/index'
    post 'comments/create'
    post 'posts/create'
    root 'posts#index'  
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#new", as: "login"
    get "logout", to: "sessions#destroy", as: "logout"
    resources :sessions, only: [:new, :create, :destroy]  
    resources :posts 
    resources :comments
    resources :users
    resources :media do
      member do
        get 'next', to: 'media#next_medium'
        get 'previous', to: 'media#prev_medium'
      end
      # collection do
      #   delete 'multiple_delete', to: 'media#multiple_delete'
      # end
    end
    mount ActionCable.server => '/cable'
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_medium, only: [:show, :edit, :update, :destroy, :next_medium, :prev_medium]
  
  def show    
    # byebug
    # @post = Post.new
    # @medium = @post.media.build
    # @medium_detail = Medium.find(params[:id])

    ViewStatisticWorker.perform(@medium.id)

    respond_to do |format|
      format.js
      # format.html
    end
  end

  def next_medium
    # byebug
    aa = Medium.new
    @new_medium = aa.next_media(@medium.id)
    # @new_medium = @medium.next_media
    respond_to do |format|
      format.js { render :new_medium }
    end
  end

  def prev_medium
    # byebug
    qq = Medium.new
    @new_medium = qq.prev_media(@medium.id)
    respond_to do |format|
      format.js { render :new_medium }
    end
  end

  private

  def set_medium
    # byebug
    @medium = Medium.find(params[:id])
  end

end

app/views/media/_form.html.erb
<%# <%= image_tag @post_attachment.avatar  %>
<%= form_for(@medium) do |f| %>
  <div class="field">
    <%= f.label :like_medium %><br>
    <%= f.file_field :like_medium %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media/_medium.html.erb
<%# <p><%= image_tag medium.link_medium_url  %>
<div class="containerDetail">
  <% if medium.link_medium? %>
    <% type = file_type(medium.link_medium_url)  %>
    <% if type == 'image'  %>
      <div class="objectMedia">
      <%= link_to '<', previous_medium_url(medium.id), remote: true %> 
      <%= link_to '>', next_medium_url(medium.id), remote: true %>
      <%= image_tag medium.link_medium_url, class: "scaledown"%>
      </div>
      <div class="objectMedia">
        <div class="comments" id= "comments_media_<%= medium.id %>">
        <% if medium.comments.present?%>  
            <%= render 'comments/comment_media', :object => medium.comments %>
        <% end %>
        </div>
        <div class="input-group">
          <div class="input-group-btn">
            <button class="btn btn-default">Add</button></button>
          </div>
          <%= form_with model: Comment  do |f| %>
            <%= f.hidden_field :post_id, :value => medium.post_id%>
            <%= f.hidden_field :medium_id, :value => medium.id%>
            <%= f.text_field :comment_content, class: "media_cmt_box form-control" %>
          <% end %>
        </div>
      </div>
    <% elsif type == 'video' %>
      <div class="objectMedia">
        <%= video_tag medium.link_medium_url, class: "scaledown"%>
      </div>
      <div class="objectMedia">
        <span >comment</span>
      </div>
    <% end  %> 
  <%end%> 
</div>
<%# <% if medium.link_medium.present?  %>
  <%# <% type = file_type(m.link_medium_url)  %>
  <%# <% if type == 'image'  %>
    <%# <%= image_tag medium.link_medium_url  %>
  <%# <% elsif type == 'video' 		 %>
    <%# <%= video_tag medium.link_medium_url  %>
  <%# <% end  %>

<%# <%end %>

app/views/media/new_medium.js.erb
$('#medium').empty();
$("<%= escape_javascript(render @new_medium) %> ").appendTo("#medium");

app/views/media/show.html.erb
<div>
  <% if @medium_detail.link_medium? %>
    <%= image_tag @medium_detail.link_medium_url, class: "scaledown"%>
  <%end%>
</div>
<div class="objectMedia">
    <div class="comments" id= "comments_media_<%= @medium_detail.id %>">
    <% if @medium_detail.comments.present?%>  
        <%= render 'comments/comment_media', :object => @medium_detail.comments %>
    <% end %>
  </div>
    <div class="input-group">
			<div class="input-group-btn">
				<button class="btn btn-default">Add</button></button>
			</div>
			<%= form_with(model: Comment, remote: true) do |f| %>
  <%= f.hidden_field :post_id, :value => @medium_detail.post_id%>
  <%= f.hidden_field :medium_id, :value => @medium_detail.id%>
  <%= f.text_field :comment_content, class: "form-control" %>
  <%# <%= f.button :submit  %>
<% end %>

app/views/media/show.js.erb
$('#showModal').modal('show');
$('#medium').empty();
$("<%= escape_javascript(render @medium) %> ").appendTo("#medium");